version: '3.5'

networks:
  app-network:
    driver: ${NETWORK_TYPE}

services:

  elasticsearch:
    image: elasticsearch:${ES_VER}
    hostname: elasticsearch
    volumes:
      - ${WORKSPACE_PATH}/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=mda-cluster
      - node.name=mda-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=mda-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${LOCAL_LISTEN_ADDR}9200:9200"
      - "${LOCAL_LISTEN_ADDR}9300:9300"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1g

  nginx:
    image: nginx:alpine
    hostname: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  mysql:
    image: mysql:${MYSQL_VER}
    hostname: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:

      # Mount devilbox user-defined cnf files in order
      # to overwrite the MySQL server configuration
      - ${WORKSPACE_PATH}/cfg/MySQL/${MYSQL_VER}:/etc/mysql/docker-default.d:ro

      # Mount MySQL Data directory
      - ${WORKSPACE_PATH}/data/MySQL-${MYSQL_VER}:/var/lib/mysql:rw
    networks:
      - app-network

  redis:
    image: 'bitnami/redis:${REDIS_VER}'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - app-network
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${WORKSPACE_PATH}/data/redis:/bitnami/redis/data
